name: DrivestNavigation

options:
  createIntermediateGroups: true
  defaultConfig: Debug

packages:
  MapboxNavigation:
    url: https://github.com/mapbox/mapbox-navigation-ios.git
    exact: 3.11.4

targets:
  DrivestNavigation:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
      - path: Resources
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.drivest.navigation
        PRODUCT_NAME: DrivestNavigation
        SWIFT_VERSION: "6.0"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_STYLE: Automatic
    configFiles:
      Debug: Configs/Debug.xcconfig
      Release: Configs/Release.xcconfig
    dependencies:
      - package: MapboxNavigation
        product: MapboxNavigationCore
      - package: MapboxNavigation
        product: MapboxNavigationUIKit
      - package: MapboxNavigation
        product: MapboxDirections

  DrivestNavigationTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests
    dependencies:
      - target: DrivestNavigation
